using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YellowKalam.Api.Data;
using YellowKalam.Api.Models;
using YellowKalam.Api.Dtos;
using System.Security.Cryptography;
using System.Text;

namespace YellowKalam.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class AppUsersController : ControllerBase
    {
        private readonly YellowKalamContext _context;

        public AppUsersController(YellowKalamContext context)
        {
            _context = context;
        }

        // GET: api/AppUsers
        [HttpGet]
        public async Task<ActionResult<IEnumerable<AppUserDto>>> GetAppUsers()
        {
            var users = await _context.AppUsers
                .AsNoTracking()
                .OrderBy(u => u.AppUserId)
                .Select(u => new AppUserDto
                {
                    AppUserId = u.AppUserId,
                    AppGroupId = u.AppGroupId,
                    AppUserCode = u.AppUserCode,
                    AppUserName = u.AppUserName,
                    IsGroupLeader = u.IsGroupLeader,
                    IsActive = u.IsActive,
                    HashedPassword = u.HashedPassword
                })
                .ToListAsync();

            return Ok(users);
        }

        // POST: api/AppUsers
        [HttpPost]
        public async Task<ActionResult<AppUserDto>> CreateAppUser(CreateAppUserDto dto)
        {
            if (string.IsNullOrWhiteSpace(dto.AppUserCode) ||
                string.IsNullOrWhiteSpace(dto.AppUserName) ||
                string.IsNullOrWhiteSpace(dto.Password))
            {
                return BadRequest("Missing required fields.");
            }

            var entity = new AppUser
            {
                AppGroupId = dto.AppGroupId,
                AppUserCode = dto.AppUserCode,
                AppUserName = dto.AppUserName,
                IsGroupLeader = dto.IsGroupLeader,
                IsActive = dto.IsActive,
                HashedPassword = HashPassword(dto.Password),
                LastPwdChangeDt = DateTime.Now,
                LastUpdated = DateTime.Now,
                UpdatedBy = "system",

                // minimal defaults for non-nullable columns
                BranchId = 0,
                LimitToBranch = "N",
                LastHostUsed = string.Empty,
                LastLoginDate = DateTime.Now,
                RowVersion = 0
                // ⚠️ DO NOT set TtimeStamp – it's a rowversion generated by SQL
            };

            _context.AppUsers.Add(entity);
            await _context.SaveChangesAsync();

            var result = new AppUserDto
            {
                AppUserId = entity.AppUserId,
                AppGroupId = entity.AppGroupId,
                AppUserCode = entity.AppUserCode,
                AppUserName = entity.AppUserName,
                IsGroupLeader = entity.IsGroupLeader,
                IsActive = entity.IsActive,
                HashedPassword = entity.HashedPassword
            };

            return CreatedAtAction(nameof(GetAppUsers), new { id = entity.AppUserId }, result);
        }

        // PUT: api/AppUsers/5
        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateAppUser(int id, UpdateAppUserDto dto)
        {
            if (id != dto.AppUserId)
                return BadRequest("ID mismatch");

            var entity = await _context.AppUsers.FindAsync(id);
            if (entity == null)
                return NotFound();

            entity.AppUserName = dto.AppUserName;
            entity.AppGroupId = dto.AppGroupId;
            entity.AppUserCode = dto.AppUserCode;
            entity.IsGroupLeader = dto.IsGroupLeader;
            entity.IsActive = dto.IsActive;
            entity.LastUpdated = DateTime.Now;
            entity.UpdatedBy = "system";

            await _context.SaveChangesAsync();
            return NoContent();
        }
        // =========================================
        // DELETE: api/AppUsers/5
        // Used by SettingsPage to delete a user
        // =========================================
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteAppUser(int id)
        {
            var entity = await _context.AppUsers.FindAsync(id);
            if (entity == null)
                return NotFound();

            _context.AppUsers.Remove(entity);
            await _context.SaveChangesAsync();

            return NoContent();
        }

        private static string HashPassword(string password)
        {
            using var sha = SHA256.Create();
            var bytes = Encoding.UTF8.GetBytes(password);
            var hash = sha.ComputeHash(bytes);
            return Convert.ToBase64String(hash);
        }
    }
}
